Repository theislab/ehrapy, pull requests merged in 2022-12, with the labels that each got.

#426 Logging instance, issue #246
  ehrapy/_settings.py
  ehrapy/anndata/anndata_ext.py
  ehrapy/core/meta_information.py
  ehrapy/data/_dataloader.py
  ehrapy/io/_write.py
  ehrapy/logging.py
  ehrapy/preprocessing/_data_imputation.py
  ehrapy/preprocessing/_encode.py
  ehrapy/preprocessing/_normalization.py
  ehrapy/preprocessing/_quality_control.py
Labels: enhancement

#429 df_to_anndata logical XOR to OR, issue #422
  ehrapy/anndata/anndata_ext.py
  tests/anndata/test_anndata_ext.py
Labels: bug

#425 fix qc_metrics bug
  ehrapy/preprocessing/_quality_control.py
  tests/preprocessing/test_quality_control.py
Labels: bug

#430 Remove PDF support
  .github/workflows/run_tests.yml
  docs/usage/usage.md
  ehrapy/io/__init__.py
  ehrapy/io/_read.py
  ehrapy/io/_utility_io.py
  poetry.lock
  pyproject.toml
  tests/io/test_read.py
Labels: enhancement, chore

#418 Add winsorize, clip quantiles and filter quantiles
  docs/usage/usage.md
  ehrapy/preprocessing/__init__.py
  ehrapy/preprocessing/_outliers.py
  tests/preprocessing/test_outliers.py
  tests/preprocessing/test_quality_control.py
Labels: enhancement, chore

#434 Add thefuzz
  ehrapy/__init__.py
  ehrapy/core/_meta_information.py
  ehrapy/core/_tool_available.py
  ehrapy/core/str_matching.py
  ehrapy/preprocessing/_data_imputation.py
  ehrapy/preprocessing/_quality_control.py
  ehrapy/tools/__init__.py
  ehrapy/tools/nlp/_medcat.py
  poetry.lock
  pyproject.toml
  tests/core/test_str_matching.py
  tests/data/test_data/dataset_1.csv
  tests/data/test_data/dataset_2.tsv
  tests/data/test_data/dataset_3.tsv
  tests/data/test_dataloader.py
  tests/data/test_datasets.py
  tests/io/test_read.py
Labels: enhancement

#435 Fix MacOS CI
  .github/workflows/run_tests.yml
Labels: bug
