Repository theislab/ehrapy, pull requests merged in 2022-03, with the labels that each got.

#327 [FEATURE] #314: Autodetect binary (0,1) columns
  ehrapy/anndata/anndata_ext.py
  ehrapy/preprocessing/encoding/_encode.py
  tests/anndata/test_anndata_ext.py
Labels: enhancement

#336 Add encoded parameter to all new datasets amd fix import
  ehrapy/data/__init__.py
  ehrapy/data/_datasets.py
Labels: bug, enhancement

#344 Fix #331: Improved autodetect docs
  ehrapy/preprocessing/encoding/_encode.py
  poetry.lock
  pyproject.toml
Labels: bug

#347 [FIX] Write .h5ad files
  ehrapy/anndata/anndata_ext.py
  ehrapy/io/_read.py
  ehrapy/io/_write.py
  ehrapy/preprocessing/encoding/_encode.py
  poetry.lock
  pyproject.toml
  tests/anndata/test_anndata_ext.py
  tests/io/test_data_io/dataset6.csv
  tests/io/test_read.py
  tests/preprocessing/test_encode.py
Labels: bug

#350 [Feature] Set index column #305
  ehrapy/anndata/anndata_ext.py
  tests/anndata/test_anndata_ext.py
Labels: enhancement

#348 [FIX] #255: Encode mutates input adata object
  ehrapy/anndata/anndata_ext.py
  ehrapy/io/_write.py
  ehrapy/preprocessing/encoding/_encode.py
  tests/preprocessing/test_encode.py
Labels: bug

#352 Add ability to compare laboratory measurements to reference values
  ehrapy/preprocessing/_quality_control.py
  ehrapy/preprocessing/laboratory_reference_tables/laposata.tsv
  poetry.lock
  tests/preprocessing/test_quality_control.py
Labels: enhancement

#355 add several datasets and change Docstring examples
  ehrapy/data/__init__.py
  ehrapy/data/_datasets.py
Labels: enhancement

#365 [#307] Improve KNN with n_neighbours parameter
  ehrapy/preprocessing/_data_imputation.py
  tests/preprocessing/test_imputation.py
Labels: enhancement

#353 add SoftImpute and IterativeSVD to imputation
  .github/workflows/run_tests.yml
  docs/usage/usage.md
  ehrapy/plot/_scanpy_pl_api.py
  ehrapy/preprocessing/__init__.py
  ehrapy/preprocessing/_data_imputation.py
  noxfile.py
  poetry.lock
  pyproject.toml
  tests/preprocessing/test_data_imputation/test_impute_iris.csv
  tests/preprocessing/test_data_imputation/test_impute_titanic.csv
  tests/preprocessing/test_imputation.py
Labels: enhancement, chore
