Repository theislab/ehrapy, pull requests merged in 2024-05, with the labels that each got.

#690 Add bias detection to preprocessing
  docs/usage/usage.md
  ehrapy/preprocessing/__init__.py
  ehrapy/preprocessing/_bias.py
  ehrapy/preprocessing/_imputation.py
  ehrapy/tools/feature_ranking/_feature_importances.py
  tests/preprocessing/test_bias.py
  tests/tools/feature_ranking/test_feature_importances.py
Labels: enhancement, chore

#714 Encoded dtype to float32 instead of np.number
  ehrapy/preprocessing/_encoding.py
Labels: bug

#715 Use __all__
  ehrapy/anndata/__init__.py
  ehrapy/data/__init__.py
  ehrapy/io/__init__.py
  ehrapy/preprocessing/__init__.py
  ehrapy/tools/__init__.py
  ehrapy/tools/cohort_tracking/_cohort_tracker.py
  tests/_scripts/cohort_tracker_test_create_expected_plots.ipynb
  tests/conftest.py
  tests/tools/_images/cohorttracker_adata_mini_flowchart_expected.png
  tests/tools/_images/cohorttracker_adata_mini_step1_use_settings_big_expected.png
  tests/tools/_images/cohorttracker_adata_mini_step1_use_settings_expected.png
  tests/tools/_images/cohorttracker_adata_mini_step1_vanilla_expected.png
  tests/tools/_images/cohorttracker_adata_mini_step2_loose_category_expected.png
  tests/tools/_images/cohorttracker_adata_mini_step2_vanilla_expected.png
  tests/tools/cohort_tracking/test_cohort_tracking.py
Labels: enhancement

#719 Simplify ehrapy
  ehrapy/preprocessing/__init__.py
  ehrapy/preprocessing/_encoding.py
  ehrapy/preprocessing/_imputation.py
  ehrapy/preprocessing/_normalization.py
  ehrapy/preprocessing/_quality_control.py
  ehrapy/tools/__init__.py
  ehrapy/tools/nlp/_translators.py
  pyproject.toml
  tests/preprocessing/test_encoding.py
  tests/preprocessing/test_imputation.py
  tests/preprocessing/test_normalization.py
  tests/tools/nlp/test_translator.py
Labels: enhancement

#721 catplot
  docs/_static/docstring_previews/catplot.png
  docs/usage/usage.md
  ehrapy/plot/__init__.py
  ehrapy/plot/_catplot.py
  tests/_scripts/catplot_create_expected_plots.ipynb
  tests/plot/_images/catplot_vanilla_expected.png
  tests/plot/test_catplot.py
Labels: enhancement

#728 Remove fancyimpute
  pyproject.toml
Labels: enhancement

#729 remove pyyaml & explicit scikit-learn
  pyproject.toml
Labels: enhancement

#735 Fix columns_obs_only & index_col
  ehrapy/anndata/_feature_specifications.py
  ehrapy/anndata/anndata_ext.py
  ehrapy/preprocessing/_encoding.py
  ehrapy/preprocessing/_quality_control.py
  tests/anndata/test_anndata_ext.py
  tests/preprocessing/test_normalization.py
  tests/tools/feature_ranking/test_rank_features_groups.py
Labels: bug

#737 Simplify conf.py
  docs/conf.py
Labels: enhancement

#739 Remove defaults to docstrings
  docs/conf.py
  ehrapy/anndata/_feature_specifications.py
  ehrapy/anndata/anndata_ext.py
  ehrapy/data/_dataloader.py
  ehrapy/data/_datasets.py
  ehrapy/io/_read.py
  ehrapy/io/_write.py
  ehrapy/plot/_missingno_pl_api.py
  ehrapy/plot/_survival_analysis.py
  ehrapy/plot/causal_inference/_dowhy.py
  ehrapy/plot/feature_ranking/_feature_importances.py
  ehrapy/preprocessing/_balanced_sampling.py
  ehrapy/preprocessing/_bias.py
  ehrapy/preprocessing/_encoding.py
  ehrapy/preprocessing/_highly_variable_features.py
  ehrapy/preprocessing/_imputation.py
  ehrapy/preprocessing/_normalization.py
  ehrapy/preprocessing/_outliers.py
  ehrapy/preprocessing/_quality_control.py
  ehrapy/preprocessing/_scanpy_pp_api.py
  ehrapy/preprocessing/_summarize_measurements.py
  ehrapy/tools/_sa.py
  ehrapy/tools/causal/_dowhy.py
  ehrapy/tools/cohort_tracking/_cohort_tracker.py
  ehrapy/tools/feature_ranking/_feature_importances.py
  ehrapy/tools/feature_ranking/_rank_features_groups.py
Labels: enhancement

#741 Add quotes to error message of features with only NaNs
  ehrapy/anndata/_feature_specifications.py
Labels: enhancement
