Repository theislab/ehrapy, pull requests merged in 2024-07, with the labels that each got.

#772 fix test: 6 refutation results
  tests/tools/causal/test_dowhy.py
Labels: bug

#774 style: == to is for type comparison
  ehrapy/anndata/_feature_specifications.py
Labels: ci, refactoring, style

#777 Fix scanpy anyrandom
  ehrapy/preprocessing/_scanpy_pp_api.py
  ehrapy/tools/_scanpy_tl_api.py
  pyproject.toml
Labels: bug

#773 loosen scipy restriction
  pyproject.toml
Labels: bug, build, dependencies, chore

#754 Fix/restrict tableone
  pyproject.toml
Labels: bug
