Repository theislab/ehrapy, pull requests merged in 2024-06, with the labels that each got.

#753 restrict tableone<=0.8.0
  pyproject.toml
Labels: bug

#756 cleaned up sep/delim issue
  ehrapy/io/_read.py
Labels: bug

#751 Consistent US spelling in docs and fix typos
  docs/contributing.md
  docs/tutorials/index.md
  ehrapy/anndata/anndata_ext.py
  ehrapy/core/_tool_available.py
  ehrapy/data/_dataloader.py
  ehrapy/io/_read.py
  ehrapy/io/_write.py
  ehrapy/plot/_catplot.py
  ehrapy/plot/_missingno_pl_api.py
  ehrapy/plot/_scanpy_pl_api.py
  ehrapy/plot/feature_ranking/_feature_importances.py
  ehrapy/preprocessing/_encoding.py
  ehrapy/preprocessing/_highly_variable_features.py
  ehrapy/preprocessing/_imputation.py
  ehrapy/preprocessing/_outliers.py
  ehrapy/preprocessing/_summarize_measurements.py
  ehrapy/tools/_sa.py
  ehrapy/tools/_scanpy_tl_api.py
  ehrapy/tools/feature_ranking/_feature_importances.py
  ehrapy/tools/feature_ranking/_rank_features_groups.py
  ehrapy/tools/nlp/_medcat.py
  tests/preprocessing/test_imputation.py
Labels: bug, documentation, breaking, chore

#758 fix alen to aalen
  docs/usage/usage.md
  ehrapy/tools/__init__.py
  ehrapy/tools/_sa.py
  tests/tools/test_sa.py
Labels: bug, chore

#770 Added new refuters
  ehrapy/tools/causal/_dowhy.py
Labels: enhancement
