Repository theislab/ehrapy, pull requests merged in 2024-01, with the labels that each got.

#638 Refactor _missing_values calculation
  ehrapy/preprocessing/_quality_control.py
Labels: enhancement

#643 Coxphfitter
  docs/usage/usage.md
  ehrapy/tools/__init__.py
  ehrapy/tools/_sa.py
  tests/tools/test_sa.py
Labels: chore

#644 Fix one-hot encoding tests
  docs/usage/usage.md
  ehrapy/preprocessing/_encode.py
Labels: bug, chore
