Repository theislab/ehrapy, pull requests merged in 2024-04, with the labels that each got.

#683 doc fix imputation: 70 instead of 30
  ehrapy/preprocessing/_imputation.py
Labels: documentation

#677 Calculation of feature importances in a supervised setting
  docs/_static/docstring_previews/feature_importances.png
  docs/usage/usage.md
  ehrapy/plot/__init__.py
  ehrapy/plot/feature_ranking/__init__.py
  ehrapy/plot/feature_ranking/_feature_importances.py
  ehrapy/tools/__init__.py
  ehrapy/tools/feature_ranking/_feature_importances.py
  tests/tools/supervised/test_feature_importances.py
Labels: enhancement

#692 Refactor outliers and IQR
  .github/workflows/run_notebooks.yml
  ehrapy/anndata/anndata_ext.py
  ehrapy/preprocessing/_imputation.py
  ehrapy/preprocessing/_outliers.py
  ehrapy/preprocessing/_quality_control.py
  ehrapy/tools/_sa.py
  tests/conftest.py
  tests/preprocessing/test_outliers.py
  tests/preprocessing/test_quality_control.py
Labels: enhancement

#694 Simplify CI
  .github/workflows/test.yml
Labels: enhancement

#700 Build RTD docs with uv
  .readthedocs.yml
  pyproject.toml
Labels: enhancement

#708 Fix feature importance warnings
  ehrapy/tools/feature_ranking/_feature_importances.py
  tests/tools/feature_ranking/test_feature_importances.py
Labels: bug
