Repository theislab/ehrapy, pull requests merged in 2024-11, with the labels that each got.

#821 Cotributing typo fix
  docs/contributing.md
Labels: bug

#830 Python 3.10+ & use uv for docs & fix RTD & support numpy 2
  .github/workflows/run_notebooks.yml
  .readthedocs.yml
  docs/_ext/edit_on_github.py
  ehrapy/_utils_doc.py
  ehrapy/anndata/anndata_ext.py
  ehrapy/data/_datasets.py
  ehrapy/plot/_scanpy_pl_api.py
  ehrapy/preprocessing/_encoding.py
  ehrapy/preprocessing/_imputation.py
  ehrapy/preprocessing/_normalization.py
  ehrapy/preprocessing/_scanpy_pp_api.py
  ehrapy/tools/_method_options.py
  ehrapy/tools/_scanpy_tl_api.py
  ehrapy/tools/causal/_dowhy.py
  ehrapy/tools/cohort_tracking/_cohort_tracker.py
  ehrapy/tools/feature_ranking/_rank_features_groups.py
  pyproject.toml
Labels: bug, enhancement

#794 Python 3.12 support
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/run_notebooks.yml
  .github/workflows/test.yml
  .readthedocs.yml
Labels: enhancement
