Repository theislab/ehrapy, pull requests merged in 2025-01, with the labels that each got.

#844 Fix CI
  .pre-commit-config.yaml
  ehrapy/__init__.py
  ehrapy/core/meta_information.py
  ehrapy/tools/feature_ranking/_rank_features_groups.py
  pyproject.toml
  tests/anndata/test_anndata_ext.py
  tests/preprocessing/test_normalization.py
Labels: bug, chore

#835 Add array type handling for normalization
  .github/workflows/run_notebooks.yml
  ehrapy/_compat.py
  ehrapy/preprocessing/_normalization.py
  pyproject.toml
  tests/preprocessing/test_normalization.py
Labels: chore

#846 Fix a typo in `pl.paga_compare`: `pos` -> `pos,`
  ehrapy/plot/_scanpy_pl_api.py
Labels: bug

#854 Update power norm test reference values
  tests/preprocessing/test_normalization.py
Labels: ci

#859 Improve submodule documentation
  docs/contributing.md
Labels: documentation

#862 Fix test_norm_power_group
  tests/preprocessing/test_normalization.py
Labels: bug, enhancement
